---
# Resource pools (what the orchestration layer allocates from)
vlan_range_start: 100
vlan_range_end: 199
subnet_pool: "10.0.0.0/8"

# Network node
net_node_trunk_interface: eth1
net_node_external_interface: eth0
net_node_external_gateway: 172.20.20.1
